# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: transaction
      POSTGRES_DB: transaction_service
      POSTGRES_PASSWORD: 123456
    ports:
    - "5433:5432"
