# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: user_service
      POSTGRES_PASSWORD: 123456
    ports:
    - "5434:5432"
